package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Dummy2_Bc'
in the project with id = 'Dummy2', and delete the patch script.
*/
create(RelativeId("Dummy2"), BuildType({
    id("Dummy2_Bc")
    name = "BC"
}))

