name: CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          foo: ${{ secrets.foo }}
          bar: ${{ vars.bar }}
